-- SESSION 1
BEGIN ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;

-- SESSION 2
BEGIN ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;

-- SESSION 1
SELECT SUM(rating)
FROM pizzeria;

-- SESSION 2
UPDATE pizzeria
SET rating = 5
WHERE name = 'Pizza Hut';
COMMIT;

-- SESSION 1
SELECT SUM(rating)
FROM pizzeria;
COMMIT;

-- SESSION 1
SELECT SUM(rating)
FROM pizzeria;

-- SESSION 2
SELECT SUM(rating)
FROM pizzeria;
